DROP TABLE IF EXISTS ASSIGNMENT ;
DROP TABLE IF EXISTS COURSE ;
DROP TABLE IF EXISTS STUDENT ;


CREATE TABLE IF NOT EXISTS STUDENT  (  
 UID VARCHAR(100) NOT NULL PRIMARY KEY,  
 USERNAME VARCHAR(100),  
 PASSWORD VARCHAR(100),   
 DOB DATE NOT NULL,  
 FIRSTNAME VARCHAR(100),  
 MIDDLENAME VARCHAR(100),    
 LASTNAME VARCHAR(100)
) ;
CREATE TABLE IF NOT EXISTS COURSE  (  
 CID VARCHAR(100) NOT NULL PRIMARY KEY,  
 COURSETITLE VARCHAR(100),  
 SEMESTER VARCHAR(100),   
 YEAR DATE NOT NULL
) ;
CREATE TABLE IF NOT EXISTS ASSIGNMENT (  
 CID VARCHAR(100) NOT NULL PRIMARY KEY,  
 COURSETITLE VARCHAR(100),  
 SEMESTER VARCHAR(100),   
 YEAR DATE NOT NULL
) ;
